# Generated by Django 2.2.13 on 2020-09-26 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso_4p',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta1', models.CharField(max_length=250)),
                ('pregunta2', models.CharField(max_length=250)),
                ('pregunta3', models.CharField(max_length=250)),
                ('pregunta4', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Caso_4p_finalizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta1', models.CharField(max_length=250)),
                ('pregunta2', models.CharField(max_length=250)),
                ('pregunta3', models.CharField(max_length=250)),
                ('pregunta4', models.CharField(max_length=250)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
