# Generated by Django 2.2.13 on 2020-06-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0002_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
    ]
