# Generated by Django 2.2.13 on 2020-06-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0003_auto_20200614_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
