# Generated by Django 2.2.13 on 2020-11-09 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retos', '0004_cuestionario_pec_cuestionario_pec_realizado_historial_emociones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario_no',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(default='Mi compañero de trabajo me pide que haga un trabajo que no me corresponde…', max_length=150)),
                ('p2', models.CharField(default='Cuando por la calle me paran para venderme algo, poner una firma, darme propaganda…', max_length=150)),
                ('p3', models.CharField(default='Cuando alguien está contando una historia y yo sé que no ha ocurrido de esa manera…', max_length=150)),
                ('p4', models.CharField(default='Mi jefe me pide que haga un trabajo que no teníamos previsto y para ello tengo que sacrificar tiempo personal…', max_length=150)),
                ('p5', models.CharField(default='Cuando me ofrecen otra copa y yo ya no quiero más…', max_length=150)),
                ('p6', models.CharField(default='Cuando me proponen ir al cine a ver una película que yo no quiero', max_length=150)),
                ('p7', models.CharField(default='Cuando me quieren vender algo que no me convence después de que me han estado atendiendo un largo rato…', max_length=150)),
                ('p8', models.CharField(default='Cuando mi pareja me propone hacer un plan que no me apetece en absoluto…', max_length=150)),
                ('p9', models.CharField(default='Si alguien que tampoco me gusta tanto me invita a salir…', max_length=150)),
                ('p10', models.CharField(default='En la sala de espera del médico o esperando una fila para pagar, alguien me pide pasar antes que yo…', max_length=150)),
                ('p11', models.CharField(default='Cuando un “listo/a” me quita el sitio de aparcamiento por el que yo estaba esperando…', max_length=150)),
                ('p12', models.CharField(default='Cuando mi familia me dice que vaya a comer con ellos un día que me viene realmente mal…', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='cuestionario_pec_realizado',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
