# Generated by Django 2.2.13 on 2020-06-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0005_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
