# Generated by Django 2.2.13 on 2020-08-15 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0008_cuestionario_cuestionariorespondido_pregunta_respuesta_respuesta_final_reto_reto_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
