# Generated by Django 2.2.13 on 2020-12-06 02:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0009_auto_20201205_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reto_finalizado',
            name='finalizado',
        ),
        migrations.RemoveField(
            model_name='reto_finalizado',
            name='reto',
        ),
        migrations.AddField(
            model_name='reto_finalizado',
            name='fecha_registrada',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reto_finalizado',
            name='respuesta',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='reto_finalizado',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
