# Generated by Django 2.2.13 on 2020-12-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0010_auto_20201205_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto_finalizado',
            name='name',
            field=models.CharField(default='', max_length=75),
        ),
    ]
