# Generated by Django 2.2.13 on 2020-12-08 02:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retos', '0011_reto_finalizado_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alegre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='caraX',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emocion_final',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emocion_inicial',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='enojado',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='triste',
        ),
        migrations.CreateModel(
            name='Estadísticas_emociones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoción_registrada', models.CharField(default='', max_length=50)),
                ('fecha_registrada', models.DateTimeField(default=datetime.date.today)),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
