# Generated by Django 2.2.13 on 2020-12-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0013_auto_20201208_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='pregunta',
            field=models.CharField(max_length=150),
        ),
    ]
