# Generated by Django 2.2.13 on 2020-12-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0014_auto_20201208_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cantidad_retos_realizados',
            field=models.IntegerField(default=0),
        ),
    ]
