# Generated by Django 2.2.13 on 2020-12-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0015_profile_cantidad_retos_realizados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cantidad_retos_realizados',
        ),
    ]
