# Generated by Django 2.2.13 on 2020-12-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0017_insignias_insignias_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestas',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='respuestas',
            name='pregunta',
            field=models.ManyToManyField(to='retos.Preguntas'),
        ),
    ]
