# Generated by Django 2.2.13 on 2020-12-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0018_auto_20201209_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insignias_usuario',
            name='insignia_obtenida',
        ),
        migrations.AddField(
            model_name='insignias_usuario',
            name='insignia_obtenida',
            field=models.ManyToManyField(to='retos.Insignias'),
        ),
    ]
