# Generated by Django 2.2.13 on 2020-12-10 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0019_auto_20201209_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='respuestas',
            name='fecha_registrada',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
