# Generated by Django 2.2.13 on 2020-12-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0022_comentarios_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reto', models.CharField(max_length=150)),
                ('frase', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='puntos',
        ),
        migrations.AddField(
            model_name='reto_finalizado',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
