# Generated by Django 2.2.13 on 2020-12-14 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0024_auto_20201212_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caso_4p',
        ),
        migrations.RemoveField(
            model_name='caso_4p_finalizado',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cuestionario_autoestima',
        ),
        migrations.RemoveField(
            model_name='cuestionario_autoestima_respondido',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cuestionario_comunicacion_efectiva',
        ),
        migrations.RemoveField(
            model_name='cuestionario_comunicacion_realizado',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cuestionario_no',
        ),
        migrations.RemoveField(
            model_name='cuestionario_no_realizado',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cuestionario_PEC',
        ),
        migrations.RemoveField(
            model_name='cuestionario_pec_realizado',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cuestionariorespondido',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='cuestionariorespondido',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='cuestionario',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuesta_final',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuesta_final',
            name='respondido',
        ),
        migrations.RemoveField(
            model_name='respuesta_final',
            name='respuesta',
        ),
        migrations.DeleteModel(
            name='Reto',
        ),
        migrations.DeleteModel(
            name='Caso_4p_finalizado',
        ),
        migrations.DeleteModel(
            name='Cuestionario',
        ),
        migrations.DeleteModel(
            name='Cuestionario_autoestima_respondido',
        ),
        migrations.DeleteModel(
            name='Cuestionario_comunicacion_realizado',
        ),
        migrations.DeleteModel(
            name='Cuestionario_no_realizado',
        ),
        migrations.DeleteModel(
            name='Cuestionario_PEC_Realizado',
        ),
        migrations.DeleteModel(
            name='CuestionarioRespondido',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.DeleteModel(
            name='Respuesta_final',
        ),
    ]
